---
language: python
python: "2.7"
#sudo: false

notifications:
    irc: "chat.freenode.net#hdbot"

before_install:
  # Make sure everything's up to date. Not possible with sudo: false
  - sudo apt-get update -qq
  - sudo apt-get install aptitude
  # Create hard to quote file for issue #13
  - echo hello >> "hard'to\"quote$file"
  - sudo chown 1234:4321 "hard'to\"quote$file"
  # Copy specific configuration file to default/main/yml
  - cp tests/travis_defaults.yml defaults/main.yml

before_script:
  - sudo ./tests/setup-tests.sh

install:
  # Install Ansible.
  - pip install ansible

  # Add ansible.cfg to pick up roles path.
  - "{ echo '[defaults]'; echo 'roles_path = ../'; echo 'callback_plugins = ./tests/callbacks/'; } >> ansible.cfg"

script:
    # The -t level1 enable quicker verification, and the level2 enables postfix
    # when installing AIDE. Thus it is not idempotent on the second launch
    # (but ok on the third). It may be a good idea to invert the section order
    # in the future.
  - ansible-playbook -i tests/inventory tests/playbook.yml --syntax-check
  - ansible-playbook -i tests/inventory tests/playbook.yml --connection=local --sudo -e "pipelining=True" -t level1
  - cp /tmp/coveralls /tmp/firstcover
  - >
    ansible-playbook -i tests/inventory tests/playbook.yml --connection=local --sudo -e "pipelining=True" -t level1
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

after_success:
  - COVERALLS_URL='https://coveralls.io/api/v1/jobs'
  - curl -v -F 'json_file=@/tmp/firstcover' "$COVERALLS_URL"
