---
language: python
python: "2.7"
#sudo: false

notifications:
    irc: "chat.freenode.net#hdbot"

before_install:
  # Make sure everything's up to date. Not possible with sudo: false
  - sudo apt-get update -qq
  - sudo apt-get install aptitude
  # Create hard to quote file for issue #13
  - echo hello >> "hard'to\"quote$file"
  - sudo chown 1234:4321 "hard'to\"quote$file"
  # Copy specific configuration file to default/main/yml
  - cp tests/travis_defaults.yml defaults/main.yml

before_script:
  - sudo apt-get install nis -qq
  # Prepare section 04
  - sudo apt-get install apport -qq
  # Prepare section 05
  - sudo apt-get install rsh-client rsh-redone-client talk -qq
  - sudo touch /etc/inetd.conf
  - echo 'shell.bla' > /tmp/inetd
  - sudo cp /tmp/inetd /etc/inetd.conf
  - echo 'start on runlevel [2345]' > /tmp/runxinit
  - sudo cp /tmp/runxinit /etc/init/xinetd.conf
  # Prepare section 06
  - sudo apt-get install avahi-daemon cups isc-dhcp-server isc-dhcp-server6 ntp slapd rpcbind nfs-kernel-server bind9 biosdevname

install:
  # Install Ansible.
  - pip install ansible

  # Add ansible.cfg to pick up roles path.
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

script:
    # The -t level1 enable quicker verification, and the level2 enables postfix
    # when installing AIDE. Thus it is not idempotent on the second launch
    # (but ok on the third). It may be a good idea to invert the section order
    # in the future.
  - ansible-playbook -i tests/inventory tests/playbook.yml --syntax-check
  - ansible-playbook -i tests/inventory tests/playbook.yml --connection=local --sudo -e "pipelining=True" -t level1
  - >
    ansible-playbook -i tests/inventory tests/playbook.yml --connection=local --sudo -e "pipelining=True" -t level1
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
