---
language: python
python: "2.7"
#sudo: false

notifications:
    irc: "chat.freenode.net#hdbot"

before_install:
  # Make sure everything's up to date. Not possible with sudo: false
  - sudo apt-get update -qq
  - sudo apt-get install aptitude

install:
  # Install Ansible.
  - pip install ansible

  # Add ansible.cfg to pick up roles path.
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

script:
  # We'll add some commands to test the role here.
  - ansible-playbook -i tests/inventory tests/playbook.yml --syntax-check --extra-vars "travis_env=True"
  - ansible-playbook -i tests/inventory tests/playbook.yml --connection=local --sudo -e "pipelining=True" --extra-vars "travis_env=True"
  - >
    ansible-playbook -i tests/inventory tests/playbook.yml --connection=local --sudo -e "pipelining=True" --extra-vars "travis_env=True"
    #| grep -q 'changed=0.*failed=0'
    #&& (echo 'Idempotence test: pass' && exit 0)
    #|| (echo 'Idempotence test: fail' && exit 1)
