---

  - name: 2.1 Create Separate Partition for /tmp (Scored)
    debug: msg="/!\ Ensure there is a separate partition dedicated to /tmp"
    tags:
      - section2
      - section2.1

  - name: 2.2 - 4 Set nodev, nosuid, noexec option for /tmp Partition (Scored)
    mount: name=/tmp state=mounted opts=nodev,nosuid,noexec
    tags:
      - section2
      - section2.2
      - section2.3
      - section2.4

  - name: 2.5 Create Separate Partition for /var (Scored)
    debug: msg="/!\ Ensure there is a separate partition dedicated to /var"
    tags:
      - section2
      - section2.5

  - name: 2.6 Bind Mount the /var/tmp directory to /tmp (Scored)
    mount: name="/var/tmp" src="/tmp" opts=bind state=mounted
    tags:
      - section2
      - section2.6

  - name: 2.7 Create Separate Partition for /var/log (Scored)
    debug: msg="/!\ Ensure there is a separate partition dedicated to /var/log"
    tags:
      - section2
      - section2.7

  - name: 2.8 Create Separate Partition for /var/log/audit (Scored)
    debug: msg="/!\ Ensure there is a separate partition dedicated to /var/log/audit"
    tags:
      - section2
      - section2.8

  - name: 2.9 Create Separate Partition for /home (Scored)
    debug: msg="/!\ Ensure there is a separate partition dedicated to /home"
    tags:
      - section2
      - section2.9

  - name: 2.10 Add nodev Option to /home (Scored)
    mount: name:/home state:mounted opts:remount,nodev
    tags:
      - section2
      - section2.10

  - name: 2.11 Add nodev Option to Removable Media Partitions (Not Scored)
    debug: msg="/!\ Ensure removable partitions have nodev option"
    tags:
      - section2
      - section2.11

  - name: 2.12 Add noexec Option to Removable Media Partitions (Not Scored)
    debug: msg="/!\ Ensure removable partitions have noexec option"
    tags:
      - section2
      - section2.12

  - name: 2.13 Add nosuid Option to Removable Media Partitions (Not Scored)
    debug: msg="/!\ Ensure removable partitions have nosuid option"
    tags:
      - section2
      - section2.13

  - name: 2.14 - 16 Add nodev Option to /run/shm Partition (Scored)
    mount: name:/run/shm state:mounted opts:remount,nodev,nosuid,noexec
    tags:
      - section2
      - section2.14
      - section2.15
      - section2.16

  - name: 2.17 Set Sticky Bit on All World-Writable Directories (Scored)
    action: command >
      'df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -type d -perm -0002 -print 2>/dev/null | xargs chmod a+t'
    tags:
      - section2
      - section2.17

  - name: 2.25 Disable Automounting (Scored)
    lineinfile: >
        dest=/etc/init/autofs.conf
        line='start on runlevel [2345]'
        regexp='^start on runlevel [2345]'
        state=absent
    tags:
      - section2
      - section2.25