---

  - name: 4.5 Activate AppArmor (install) (Scored)
    apt: >
        name=apparmor
        state=present
    tags:
      - section4
      - section4.5

  - name: 4.5 Activate AppArmor (start) (Scored)
    service: >
        name=apparmor
        state=started
    tags:
      - section4
      - section4.5

  - name: 4.5 Activate AppArmor (profiles loaded) (Scored)
    shell: 'apparmor_status | grep "0 profiles are loaded"'
    register: profiles_loaded
    failed_when: profiles_loaded.rc == 0
    changed_when: False
    tags:
      - section4
      - section4.5

  - name: 4.5 Activate AppArmor (complain) (Scored)
    shell: 'apparmor_status | grep "0 processes are in complain mode."'
    register: complain_processes
    failed_when: complain_processes.rc == 1
    changed_when: False
    tags:
      - section4
      - section4.5

    #"The unconfined processes should be restarted after enforce"
  - name: 4.5 Activate AppArmor (unconfined) (Scored)
    shell: 'apparmor_status | grep "0 processes are unconfined but have a profile defined."'
    register: unconfined_processes
    failed_when: unconfined_processes.rc == 1
    changed_when: False
    tags:
      - section4
      - section4.5

  - name: 4.5 Activate AppArmor (enforce install) (Scored)
    apt: >
        name=apparmor-utils
        state=present
    tags:
      - section4
      - section4.5

  - name: 4.5 Activate AppArmor (enforce) (Scored)
    shell: 'aa-enforce /etc/apparmor.d/*'
    register: aaenforce_rc
    failed_when: aaenforce_rc.rc == 1
    changed_when: False
    tags:
      - section4
      - section4.5
